# Generated by Django 5.2 on 2025-04-20 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitKilimall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('prix', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('product_url', models.URLField(blank=True, max_length=500, null=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
